name: Rulesets-Update

# only trigger on pull request closed events
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  manual_run:

    runs-on: ubuntu-latest
    steps:
    - run: |
        echo QueryPack Update #${{ github.event.number }} started
        
    # checks-out the repository under $GITHUB_WORKSPACE, so this job can access it
    - uses: actions/checkout@v2
    
    # run the script and send to zentral API
    - name: Push one or more json QueryPacks
      env:
        ZTL_API_TOKEN: ${{secrets.ZTL_API_TOKEN}}
        ZTL_FQDN: ${{secrets.ZTL_FQDN}}
      run: |
          ./scripts/rulesets-update.sh
